#wrench_topic    : "filtered_wrench_base"

sampling_time: 0.008

K_tras: 0.007 #0.00005
K_rot: 0.0005 #0.0000001

base_link: panda_link0
tool_link: panda_hand

max_fl: 0.831

wrench_topic    : franka_state_controller/F_ext
dwrench_topic   : delta_force
vel_topic       : current_velocity
pos_topic       : franka_state_controller/franka_states
alpha_topic     : alpha
bool_topic      : flag
assistance_topic: assistance
reference_traj_topic  : human_ref

robot_has_human_reference: True
update_Kest: update_Kest

n_of_wrench_bias_samples: 100
norm_deadband: 0.05 # Newtons


#K_assistance: 0.0002
#K_assistance: 0.0001
#K_assistance: 0.0001







